" pyspud Vim Settings
"
" State the obvious
set nocompatible

" Use vim-pathogen by tpope
" https://github.com/tpope/vim-pathogen
source ~/settings/vim/bundle/pathogen/autoload/pathogen.vim
call pathogen#infect('~/settings/vim/bundle')
syntax on
filetype plugin indent on
"call pathogen#helptags()

" Allow easy editing of vimrc
" http://stackoverflow.com/questions/2400264/is-it-possible-to-apply-vim-configurations-without-restarting
nmap <leader>v :e $MYVIMRC<CR>
if has("autocmd")
    augroup myvimrchooks
        au!
        autocmd bufwritepost .vimrc source $MYVIMRC
    augroup END
endif

" Why does Gvim need menus and icon bar?
" It doesn't, remove them!
set guioptions-=T
set guioptions-=m
" Remove GUI scroll bars
set guioptions-=r
set guioptions-=R
set guioptions-=l
set guioptions-=L

" Show some context when scrolling
set scrolloff=2
set sidescrolloff=3
set sidescroll=1

" Display Status line at all times
set laststatus=2

" Use example status line from fugitive
set statusline=%<%f\ %h%m%r%{fugitive#statusline()}%=%-14.(%l,%c%V%)\ %P

" Use Solerized dark
" https://github.com/altercation/vim-colors-solarized
set background=dark
colorscheme solarized

