" pyspud Vim Settings
"
" State the obvious
set nocompatible

" Allow easy editing of vimrc
" http://stackoverflow.com/questions/2400264/is-it-possible-to-apply-vim-configurations-without-restarting
nmap <leader>v :e $MYVIMRC<CR>
if has("autocmd")
    augroup myvimrchooks
        au!
        autocmd bufwritepost .vimrc source $MYVIMRC
    augroup END
endif

" Include the vimfiles from my settings repo in the runtimepath
set runtimepath=~/settings/vim,$VIMRUNTIME

" Why does Gvim need menus and icon bar?
" It doesn't, remove them!
set guioptions-=T
set guioptions-=m

