" pyspud Vim Settings
"
" State the obvious
set nocompatible

" Include the vimfiles from my settings repo in the runtimepath
set runtimepath=~/settings/vim,$VIMRUNTIME

" Use vim-pathogen by tpope
" https://github.com/tpope/vim-pathogen
call pathogen#runtime_append_all_bundles()
call pathogen#helptags()

" Allow easy editing of vimrc
" http://stackoverflow.com/questions/2400264/is-it-possible-to-apply-vim-configurations-without-restarting
nmap <leader>v :e $MYVIMRC<CR>
if has("autocmd")
    augroup myvimrchooks
        au!
        autocmd bufwritepost .vimrc source $MYVIMRC
    augroup END
endif

" Why does Gvim need menus and icon bar?
" It doesn't, remove them!
set guioptions-=T
set guioptions-=m

" Use Solerized dark
" https://github.com/altercation/vim-colors-solarized
syntax enable
set background=dark
colorscheme solarized

