# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/bin:$HOME/android-sdk:$HOME/android-sdk/tools:$HOME/android-sdk/platform-tools
PATH=$PATH:$HOME/.gem/ruby/1.8/bin

export PATH
